# Meta
description: A geeker blog.
keywords: hexo,theme,icer,ggice

# Navigation
navigation:
- name: home
  slug: home
  url: /
- name: web development
  slug: web development
  url: /tags/web-development/
- name: soft
  slug: soft
  url: /tags/soft/
- name: os
  slug: os
  url: /tags/os/
- name: archives
  slug: archives
  url: /archives/
- name: README
  slug: README
  url: /README/

# Friendly link
links:
  # - name: Tian1x0
  #   url: http://1x0.xyz/
  # - name: Hankzhou
  #   url: http://www.royalmice.com/hankzhou/
  # - name: 设计有点货
  #   url: http://sjydh.me/
  - name: Web fundamentals
    url: https://developers.google.com/web/fundamentals/

# Social account
social:
- slug: twitter
  url: https://twitter.com/iggice
- slug: github
  url: https://github.com/ggice
- slug: lofter
  url: http://ggice.lofter.com/
- slug: facebook
  url: # https://www.facebook.com/some
- slug: linkedin
  url: # https://www.linkedin.com/some
- slug: weibo
  url: #http://weibo.com/309683593
- slug: tumblr
  url: #http://ggice.tumblr.com/
- slug: dribbble
  url: https://dribbble.com/ggice
- slug: email
  url: mailto:i@ice.gs
- slug: rss
	url: /atom.xml

# Google analytics
# google_analytics: UA-93986029-1

# Baidu analytics
baidu_analytics: 403460ed7637fb6c4a9e09a74e662ca0

# Local search
local_search:
  enable: true

# Favicon
#favicon: /image/favicon.ico